include ../common.mak

DATADIR   = $(TMT_ROOT)/share/data/resources/hamledt
#DATADIR   = /ha/work/people/masek/hamledtdata

A_LANGUAGES = ta
# for (non-parallel) afuns statistics on just one language

# LANGS =
# for tests ('*' by default)