include ../common.mak

DATADIR = /ha/projects/tectomt_shared/data/archive/hamledt/1.5_2014-02-15_treex-r11606

A_LANGUAGE =
# for (non-parallel) afuns statistics on just one language

# LANGS =
# for tests ('*' by default)